#!/usr/bin/perl

use v5.38.0;  # Current perl version from GH CI runner (Ubuntu 24.04LTS)
use strict;
use warnings;

use List::Util qw< any >;
use HTTP::Tiny;
use JSON::PP qw< decode_json >;

my $repo    = $ENV{GITHUB_REPOSITORY};
my $package = $ENV{PACKAGE_NAME};
my $config;
my $pkgbase;
my $pkgver;
my $upstream_url;
my $package_url;

sub err ($msg)
{
    warn "$pkgbase: $msg\n";
    exit 1;
}

sub info ($msg)
{
    print "$pkgbase: $msg\n";
}

sub add_job_summary ($msg)
{
    my $fname = $ENV{GITHUB_STEP_SUMMARY} // '';

    open my $fh, '>>', $fname
      or die "Failed to append to $fname: $!";

    print $fh "$msg\n";
    close $fh or die $!;
}

sub list_issue (%opts)
{
    my ( $type, $search, $label ) = @opts{ qw< type search label > };

    my @cmd = (
        'gh',       'issue list',
        '--repo',   $repo,
        '--search', qq{"author:app/aur-bump-bot '$search' in:title"},
        '--label',  qq{'$label'},
        '--state',  'open',
        '--limit',  '1',
        '--json',   'number',
        '--jq',     '.[].number',
    );

    chomp( my $issue_num = qx(@cmd) );

    if ( $? == 0 ) {
        return $issue_num;
    }
    else {
        err("failed to check $type issue for $pkgbase");
    }
}

sub view_issue ( $type, $issue_num )
{
    my @cmd = (
        'gh', 'issue', 'view',
        $issue_num,
        '--repo', $repo,
        '--json', 'body',
        '--jq',   '.body',
    );

    chomp( my $issue = qx(@cmd) );

    if ( $? == 0 ) {
        return $issue;
    }
    else {
        err("failed to fetch $type issue #$issue_num");
    }
}

sub edit_issue (%opts)
{
    my ( $type, $issue_num, $title, $body ) = @opts{ qw< type issue title body > };

    info("updating $type issue #$issue_num with new versions");

    my @cmd = (
        'gh', 'issue', 'edit',
        $issue_num,
        '--repo',  $repo,
        '--title', $title,
        '--body',  $body,
    );

    system(@cmd) == 0
      or err("failed to update $type issue #$issue_num");

    my $msg = "- Updated $type issue #$issue_num for $pkgbase";
    add_job_summary($msg);
}

sub create_issue (%opts)
{
    my ( $type, $label, $title, $body ) = @opts{ qw< type label title body > };

    info("creating $type issue");

    my @cmd = (
        'gh',      'issue', 'create',
        '--repo',  $repo,
        '--label', $label,
        '--title', $title,
        '--body',  $body,
    );

    system(@cmd) == 0
      or err("failed to create $type issue");

    my $msg = "- Created $type issue for $pkgbase";
    add_job_summary($msg);
}

sub close_issue (%opts)
{
    my ( $type, $issue_num ) = @opts{ qw< type issue > };

    info("closing existing issue #$issue_num");

    my @cmd = (
        'gh', 'issue', 'close',
        $issue_num,
        '--repo',    $repo,
        '--comment', "Current version $pkgver is latest, closing the issue.",
    );

    system(@cmd) == 0
      or err("failed to close $type issue #$issue_num");

    my $msg = "- Closed $type issue #$issue_num for $pkgbase";
    add_job_summary($msg);
}

sub update_or_create_issue (%opts)
{
    my ( $type, $issue_num, $label, $title, $body, $upstream_version ) =
      @opts{ qw< type issue label title body upver > };

    if ( $issue_num ne '' ) {
        # Extract versions from existing issue type.

        my $existing_body = view_issue( 'epoch', $issue_num );

        my ($existing_pkgver) = $existing_body =~ /^pkgver: ([^\n]+)$/m;
        err('failed to get existing pkgver version')
          unless defined $existing_pkgver;

        my ($existing_upstream) = $existing_body =~ /^upstream_version: ([^\n]+)$/m;
        err('failed to get existing upstream version')
          unless defined $existing_upstream;

        # Only update if versions have changed.
        if ( $existing_pkgver ne $pkgver || $existing_upstream ne $upstream_version ) {
            edit_issue(%opts);
        }
        else {
            my $same_issue = "issue #$issue_num already has current version info";
            my $msg        = "- \u$type $same_issue";

            info("$type $same_issue");
            add_job_summary($msg);
        }
    }
    else {
        create_issue(%opts);
    }
}

sub check_pkg_version ()
{
    # Get upstream version using nvchecker.
    my @cmd = (
        'nvchecker',
        '--file', $config,
        '--logger=json',
        '2> /dev/null',
        '| jq',
        '--raw-output',
        '--exit-status',
        qq{'select(.name == "'"$pkgbase"'") | .version'},
        '2> /dev/null',
    );

    chomp( my $upstream_version = qx(@cmd) );

    if ( $? == 0 ) {
        if ( $upstream_version ne '' && $upstream_version ne 'null' ) {
            chomp( my $result = qx(vercmp $upstream_version $pkgver) );

            err("failed to compare version $upstream_version against $pkgver")
              unless $? == 0;

            # Check if package out-of-date issue exists.
            my %ood = (
                type   => 'out-of-date',
                search => "$pkgbase - new version: ",
                label  => 'package out-of-date',
                upver  => $upstream_version,
            );
            $ood{issue} = list_issue(%ood);

            # Check if package epoch issue exists.
            my %epoch = (
                type   => 'epoch',
                search => "$pkgbase - version mismatch",
                label  => 'package needs-epoch',
                upver  => $upstream_version,
            );
            $epoch{issue} = list_issue(%epoch);

            if ( $result == 0 ) {
                info("current version $pkgver is latest");

                close_issue(%ood)   if $ood{issue} ne '';
                close_issue(%epoch) if $epoch{issue} ne '';
            }
            elsif ( $result < 0 ) {
                info("current version $pkgver is newer than $upstream_version");

                $epoch{title} = $epoch{search};
                $epoch{body}  = <<~"END";
                    pkgbase: $pkgbase
                    pkgver: $pkgver
                    upstream_version: $upstream_version
                    upstream_url: $upstream_url
                    package_url: $package_url

                    > [!NOTE]
                    > The pkgver version is newer than upstream, this means:
                    > - Upstream changed versioning schemes
                    > - nvchecker is pointing to the wrong source
                    > - An `epoch` bump is needed
                    >
                    > Since this breaks pacman'\''s version comparison logic, review *.nvchecker.toml* and consider adding/incrementing `epoch` in *PKGBUILD*.
                    END

                update_or_create_issue(%epoch);
            }
            elsif ( $result > 0 ) {
                info("upgrade from version $pkgver to upstream_version");

                $ood{title} = "$ood{search}$upstream_version";
                $ood{body}  = <<~"END";
                    pkgbase: $pkgbase
                    pkgver: $pkgver
                    upstream_version: $upstream_version
                    upstream_url: $upstream_url
                    package_url: $package_url
                    END

                update_or_create_issue(%ood);
            }
        }
        else {
            err('failed to get upstream version');
        }
    }
    else {
        err('nvchecker failed to fetch upstream version');
    }
}

# If the AUR package already exists in the official repo, do not check the upstream
# version but create an issue informing the packager to submit a deletion request,
# because a Package Maintainer could create an existing AUR package without checking
# or never bother to delete it.
#
# TODO:
#   To close resolved issues, maybe create a check outside the CI matrix which
#   iterates through the 'duplicate' issues, then check every package from them
#   to confirm if they still exist on AUR. But it isn't worth for now, since this
#   problem seems to be rare.
sub is_official_pkg ()
{
    # Check if package duplicate issue exists.
    my %dupe = (
        type   => 'duplicate',
        search => "$pkgbase - exists in official repo",
        label  => 'package duplicate',
    );
    my $issue = list_issue(%dupe);

    if ( defined $issue && $issue ne '' ) {
        my $same_issue = "issue #$issue already exists";
        my $msg        = "- \u$dupe{type} $same_issue";

        info("$dupe{type} $same_issue");
        add_job_summary($msg);

        exit 0;
    }
    else {
        my $query = "https://archlinux.org/packages/search/json/?name=$package";
        my $resp  = HTTP::Tiny->new->get($query);

        err("failed to fetch $dupe{type} issue query: $query")
          unless $resp->{success};

        my $json = decode_json( $resp->{content} );
        my $res  = $json->{results};

        if ( scalar $res->@* > 0 ) {
            info('package exists in official repo');

            my $repos   = $res->[0]{repo};
            my $arch    = $res->[0]{arch};
            my $pkg_url = "https://archlinux.org/packages/$repos/$arch/$package";

            $dupe{title} = $dupe{search};
            $dupe{body}  = <<~"END";
                pkgbase: $pkgbase
                pkgver: $pkgver
                upstream_version:
                upstream_url: $upstream_url
                package_url: $package_url

                > [!NOTE]
                > [$pkgbase]($pkg_url) already exists in the official repository. This means that a Package Maintainer created this package without checking or did not bother to delete it.
                >
                > Since this is against the [rules](https://wiki.archlinux.org/title/AUR_submission_guidelines#Rules_of_submission), it is recommended to submit a [deletion request](https://wiki.archlinux.org/title/AUR_submission_guidelines#Deletion).
                END

            create_issue(%dupe);
            exit 0;
        }
        else {
            info('package does not exist in official repo');
        }
    }
}

sub parse_srcinfo ()
{
    chdir $package
      or die "Failed to change directory to $package: $!";

    $config = '.nvchecker.toml';
    foreach my $file ( 'PKGBUILD', $config ) {
        if ( !-f $file ) {
            warn "$file does not exist\n";
            exit 1;
        }
    }

    my $fname = '.SRCINFO';
    open my $fh, '<:encoding(UTF-8)', $fname
      or die "Failed to open $fname: $!";

    chomp( my @lines = <$fh> );
    close $fh or die $!;

    my @VARS = (
        qw<
            pkgbase
            pkgver
            url
        >
    );

    my %srcinfo_meta;
    foreach my $line (@lines) {
        next if $line eq '';

        my ( $key, $val ) = split / = /, $line;
        next unless defined $val;
        $key =~ s{\A\t}{};

        if ( any { $key eq $_ } @VARS ) {
            $srcinfo_meta{$key} = $val;
            next;
        }

        push $srcinfo_meta{$key}->@*, $val;
    }

    $pkgbase      = $srcinfo_meta{pkgbase} // $srcinfo_meta{pkgname};
    $pkgver       = $srcinfo_meta{pkgver};
    $upstream_url = $srcinfo_meta{url};
    $package_url  = "https://aur.archlinux.org/packages/$pkgbase";
}

# Clone the GH mirror repo and fallback to AUR to reduce load in Arch servers
# and avoid rate limiting.
sub clone_pkg ()
{
    my %repos = (
        gh => {
            url => 'https://github.com/archlinux/aur',
            cmd => [
                'git', 'clone',
                '--single-branch',
                '--branch', $package,
                'https://github.com/archlinux/aur.git',
                $package,
            ],
        },
        aur => {
            url => 'https://aur.archlinux.org/',
            cmd => [
                'git', 'clone',
                "https://aur.archlinux.org/$package.git",
            ],
        },
    );

    if ( system( $repos{gh}{cmd}->@* ) != 0 ) {
        my $err = "Failed to clone $package from";
        warn "$err $repos{gh}{url}\n";

        if ( system( $repos{aur}{cmd}->@* ) != 0 ) {
            warn "$err $repos{aur}{url}\n";
            exit 1;
        }
    }
}

print "Checking $package version\n";

clone_pkg();
parse_srcinfo();
is_official_pkg();
check_pkg_version();
