#!/usr/bin/perl

use v5.38.0;
use strict;
use warnings;

use HTTP::Tiny;
use JSON::PP;

my $MAINTAINER = 'ryoskzypu';
my $url        = "https://aur.archlinux.org/rpc/v5/search/$MAINTAINER?by=maintainer";

my $res = HTTP::Tiny->new->get($url);
die "Failed to fetch AUR\n" unless $res->{success};

if ( length $res->{content} ) {
    my $json = decode_json( $res->{content} );

    die "No packages found from $MAINTAINER\n"
      unless scalar $json->{results}->@*;

    my @pkgs;
    foreach my $pkg ( $json->{results}->@* ) {
        push @pkgs, $pkg->{Name}
          if $pkg->{Name} !~ /-(?> bzr | cvs | darcs | git | hg | svn )\z/x;  # Exclude VCS pkgs
    }

    my $pkgs_cnt = scalar @pkgs;
    my $matrix   = encode_json \@pkgs;

    my $info = <<~"END";
        - Maintainer: $MAINTAINER
        - Found $pkgs_cnt packages: $matrix
        END

    print $info;

    open my $out, '>>', $ENV{GITHUB_OUTPUT} or die $!;
    print $out "packages=$matrix\n";
    close $out or die $!;

    open my $summ, '>>', $ENV{GITHUB_STEP_SUMMARY} or die $!;
    print $summ $info;
    close $summ or die $!;
}
else {
    die "No response content\n";
}
