name: 'AUR package update checker'

on:
  schedule:
    - cron: '0 0 * * Sun'  # Weekly at midnight UTC.

  workflow_dispatch:

jobs:
  fetch-packages:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.fetch.outputs.packages }}

    steps:
      - name: 'Install dependencies'
        run: |
          sudo apt update
          sudo apt install -y libio-socket-ssl-perl  # HTTP::Tiny TLS support

      - uses: actions/checkout@v6
      - name: 'Fetch AUR packages from maintainer'
        id: fetch
        run: |
          chmod +x fetch_pkgs
          ./fetch_pkgs

  check-packages:
    needs: fetch-packages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJson(needs.fetch-packages.outputs.packages) }}

      max-parallel: 4

    steps:
      - name: 'Generate GitHub App token'
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 'Install + cache apt dependencies'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libio-socket-ssl-perl makepkg nvchecker
          version: 1.0

      - uses: actions/checkout@v6
      - name: 'Check package version'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PACKAGE_NAME: ${{ matrix.package }}

        shell: bash
        run: |
          chmod +x check_pkg
          ./check_pkg
