name: 'AUR package update checker'

on:
  schedule:
    - cron: '0 0 * * Sun'  # Weekly at midnight UTC.

  workflow_dispatch:

jobs:
  fetch-packages:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.fetch.outputs.packages }}

    steps:
      - name: 'Install dependencies'
        run: |
          sudo apt update
          sudo apt install -y libio-socket-ssl-perl  # HTTP::Tiny TLS support

      - name: 'Fetch AUR packages from maintainer'
        id: fetch
        shell: bash
        run: |
          packages=$(
              perl -MHTTP::Tiny -MJSON::PP -E '
                  my $MAINTAINER = q{ryoskzypu};

                  my $res = HTTP::Tiny->new->get("https://aur.archlinux.org/rpc/v5/search/$MAINTAINER?by=maintainer");
                  die "Failed to fetch AUR\n" unless $res->{success};

                  if ( length $res->{content} ) {
                      my $json = decode_json( $res->{content} );

                      die "No packages found from $MAINTAINER\n"
                        unless scalar $json->{results}->@*;

                      my @pkgs;
                      push @pkgs, $_->{Name} foreach $json->{results}->@*;

                      my $matrix = encode_json \@pkgs;
                      print $matrix;
                  }
                  else {
                    die "No response content\n";
                  }
              '
          )
          printf 'packages=%s\n' "$packages" >> $GITHUB_OUTPUT
          printf '%s\n' "Found packages: $packages"

  check-packages:
    needs: fetch-packages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJson(needs.fetch-packages.outputs.packages) }}

      max-parallel: 5

    steps:
      - name: 'Install dependencies'
        run: |
          sudo apt update
          sudo apt install -y makepkg jq

      - name: Check package version
        shell: bash
        run: |
          package=${{ matrix.package }}
          printf '%s\n' "Checking $package version"

          git clone https://aur@aur.archlinux.org/"$package".git
          cd "$package" || exit 1

          # Based on 'pkgctl version check' (/usr/share/devtools/lib/version/check.sh)

          set -o pipefail

          # Reset common PKGBUILD variables.
          unset pkgbase pkgname arch source pkgver pkgrel validpgpkeys

          # Extract version from PKGBUILD.
          source ./PKGBUILD
          pkgbase=${pkgbase:-$pkgname}

          # Get upstream version using nvchecker.
          if upstream_version=$(
              nvchecker \
                  --file .nvchecker.toml \
                  --logger=json \
                  --failures \
                  2> /dev/null \
              | jq \
                  --raw-output \
                  --exit-status \
                  'select(.name == "'"$pkgbase"'") | .version' \
                  2> /dev/null
          )
          then
              if [[ -n $upstream_version && $upstream_version != 'null' ]]; then
                  if ! result=$(vercmp "$upstream_version" "$pkgver"); then
                      printf '%s\n' "$pkgbase: failed to compare version $upstream_version against $pkgver" >&2
                      exit 1
                  fi

                  if (( result == 0 )); then
                      printf '%s\n' "$pkgbase: current version $pkgver is latest"
                  elif (( result < 0 )); then
                      printf '%s\n' "$pkgbase: current version $pkgver is newer than $upstream_version"
                  elif (( result > 0 )); then
                      printf '%s\n' "$pkgbase: upgrade from version $pkgver to $upstream_version"
                  fi
              else
                  printf '%s\n' "$pkgbase: failed to get upstream version" >&2
                  exit 1
              fi
          else
              printf '%s\n' "$pkgbase: nvchecker failed to fetch upstream version" >&2
              exit 1
          fi
